### PR TITLE
Add commonjs

### PR DESCRIPTION
**Pull request by mjlescano**
For Browserify/RequireJS/WebPack support :)

### CODE REVIEW

**Comment by sanojian** [comment]
Thanks I was meaning to do this.

**Comment by mjlescano** [comment]
I would suggest to also write it on ES6, using [Babel](https://babeljs.io/). Let me know, I'm glad to do it :)

**Comment by sanojian** [comment]
Why is that a good idea?  I am ignorant on this topic.  Can you enlighten me?

**Comment by mjlescano** [comment]
`ECMAScript` (`ES` for short) is the specification of how `JavaScript` should be written and `ES6` is the latest Standard since last month. It has a lot of new features, including `classes`, `arrow functions`, etc. [Here's](http://www.2ality.com/2014/08/es6-today.html) a very good article that explains it in depth, also that same blog has a lot of other good articles.

With [Babel](https://babeljs.io/) you can write code in `ES6` and transpile it to `ES5` and take advantage of all the new features without losing compatibility with old browsers.

**Pull request merged**
